services:
  db:
    image: postgres:15
    container_name: desafio2_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - desafio2_data:/var/lib/postgresql/data
      - ./docker.sql:/docker-entrypoint-initdb.d/docker.sql

volumes:
  desafio2_data: