services:
  service_a:
    build: ./service_a
    ports:
      - "5001:5000"

  service_b:
    build: ./service_b
    ports:
      - "6001:6000"
    depends_on:
      - service_a

networks:
  default:
    name: desafio4_net