services:
  service_users:
    build: ./service_users
    ports:
      - "5001:5000"

  service_orders:
    build: ./service_orders
    ports:
      - "5002:5000"

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - service_users
      - service_orders

networks:
  default:
    name: desafio5_net